/*
	YOU HAVE TO ENABLE FILEPATCHING TO USE THE USERCONFIG FILE	
*/

/*
	WHITELIST PLAYER UID (IT IS THE NUMBER IN THE STEAM-PROFILE LINK)
	EXAMPLE 1: SLZ_whitelist = ["7656119797714444"];
	EXAMPLE 1: SLZ_whitelist = ["7656119797714444", "7656119797715555"];
*/
SLZ_whitelist = ["76561198027741420"];

/*
	YOU CAN ADD ARRAYS OF OBJECTS OR CODE WITH ENGINE COMMANDS LIKE ALLUNITS, PLAYABLEUNITS.......
	EXAMPLE 1: SLZ_objects = [{allUnits}, {vehicles}, {allDead}];
	EXAMPLE 2: SLZ_objects = [{playableUnits}];
	EXAMPLE 3: SLZ_objects = [{playableUnits}, [veh1, veh2, veh3,.....]];
*/
SLZ_objects = [{playableUnits}, {allUnits}, {vehicles}, {allDead}]; // DEFAULT = []

/*
	IF YOU SET THIS VARIABLE TO TRUE ALL CREATED OBJECTS WILL BE ADDED TO THE OTHER MOD CURATORS
*/
SLZ_sharedObjects = false; // DEFAULT = FALSE

/*
	ADD ALL AVAILABLE ADDONS FOR MOD CURATORS (E.G. ADDS ACE ZEUS MODULES AND STUFF LIKE CRATES)
*/

SLZ_addALLAddons = true; // DEFAULT = TRUE